import type {
    ControlPosition,
    ExpressionSpecification,
    LayerSpecification,
    Map,
    VectorSourceSpecification
} from 'maplibre-gl';

/** Scheme used to turn the RGB channels of a DEM pixel into metres. */
export type DemEncoding = 'terrarium' | 'mapbox';

export interface DemTile {
    width: number;
    height: number;
    /** Elevations in row-major order. */
    data: Float32Array;
}

export interface FetchResponse {
    data: Blob;
    cacheControl?: string;
    expires?: string;
}

export type GetTileFunction = (
    url: string,
    abortController: AbortController
) => Promise<FetchResponse>;

export type DecodeImageFunction = (
    blob: Blob,
    encoding: DemEncoding,
    abortController: AbortController
) => Promise<DemTile>;

export interface DemSourceOptions {
    /** Remote DEM URL containing `{z}`, `{x}`, and `{y}` placeholders. */
    url: string;
    /** Strictly increasing band boundaries. */
    thresholds: number[];
    /** One color per output band, or a color interpolator sampled once per band. Uses a blue ramp by default. */
    colors?: IsobandColors;
    /** Include the unbounded band below the first threshold. Defaults to false. */
    includeLower?: boolean;
    /** Include the unbounded band above the final threshold. Defaults to true. */
    includeUpper?: boolean;
    /** DEM pixel encoding. Defaults to `terrarium`. */
    encoding?: DemEncoding;
    /** Maximum zoom available from the DEM source. Defaults to 12. */
    maxzoom?: number;
    /** Number of most-recent DEM and generated tiles retained. Defaults to 100. */
    cacheSize?: number;
    /** Fetch timeout in milliseconds. Defaults to 10,000. */
    timeoutMs?: number;
    /** Prefix used for MapLibre protocol names. Defaults to `dem`. */
    id?: string;
    /** Vector source-layer name. Defaults to `isobands`. */
    layer?: string;
    /** Vector-tile coordinate extent. Defaults to 4096. */
    extent?: number;
    /** Extra output in tile pixels, used to hide seams. Defaults to 1. */
    buffer?: number;
    /** Advanced/test hook for fetching DEM images. */
    getTile?: GetTileFunction;
    /** Advanced/test hook for decoding DEM images. */
    decodeImage?: DecodeImageFunction;
}

export interface IsobandProperties {
    /** Zero-based position in the configured output-band sequence. */
    band: number;
    /** Inclusive lower boundary; absent on the unbounded lower band. */
    min?: number;
    /** Exclusive upper boundary; absent on the unbounded upper band. */
    max?: number;
}

/** One configured output band, ordered from the lowest to the highest values. */
export interface IsobandBand extends IsobandProperties {
    /** Color assigned to this band by a style palette. */
    color: string;
}

/** Produces one color for a normalized position from 0 through 1. */
export type IsobandColorInterpolator = (
    position: number,
    band: number,
    bandCount: number
) => string;

/** An exact color per band, or a function sampled once per band. */
export type IsobandColors = readonly string[] | IsobandColorInterpolator;

/** MapLibre expression generated to color features by their `band` property. */
export type IsobandFillColorExpression = ExpressionSpecification;

export type IsobandFillLayerSpecification = Extract<LayerSpecification, {type: 'fill'}>;
type FillPaintSpecification = NonNullable<IsobandFillLayerSpecification['paint']>;

export interface IsobandStyleOptions {
    /** One color per output band, or a color interpolator. Uses a sequential blue ramp by default. */
    colors?: IsobandColors;
    /** Color used if a feature has an unknown band number. Defaults to transparent. */
    fallbackColor?: string;
}

export interface IsobandLayerOptions extends Pick<IsobandStyleOptions, 'fallbackColor'> {
    /** MapLibre layer id. */
    id: string;
    /** Id of the MapLibre source created from `getSourceSpecification()`. */
    source: string;
    /** Additional fill paint properties. `fill-color` is generated by the plugin. */
    paint?: Omit<FillPaintSpecification, 'fill-color'>;
    /** Fill layer layout properties. */
    layout?: IsobandFillLayerSpecification['layout'];
    minzoom?: number;
    maxzoom?: number;
}

export interface IsobandLegendOptions {
    /** Legend heading. Defaults to `Elevation`; set to false to omit it. */
    title?: string | false;
    /** Unit appended to every generated range label. */
    unit?: string;
    /** Customize formatting of numeric band boundaries. */
    formatValue?: (value: number) => string;
    /** Customize the complete label for a band. */
    formatLabel?: (band: Readonly<IsobandBand>) => string;
    /** Additional class added to the legend container. */
    className?: string;
    /** Accessible label for the control. Defaults to the title or `Contour legend`. */
    ariaLabel?: string;
    /** Default corner used when adding the control. Defaults to `bottom-left`. */
    position?: ControlPosition;
}

export interface AddIsobandLayerOptions extends Omit<IsobandLayerOptions, 'source'> {
    /** Id used when adding the generated vector source. */
    sourceId: string;
    /** Add a generated legend, optionally customized. Defaults to true. */
    legend?: boolean | IsobandLegendOptions;
    /** Layer id before which the contour layer is inserted. */
    beforeId?: string;
}

export interface AddedIsobandLayer {
    readonly sourceId: string;
    readonly layerId: string;
    /** The generated legend control, when enabled. */
    readonly legend?: import('./legend-control.js').IsobandLegendControl;
    /** Removes the layer, source, and legend added by `DemSource.addTo()`. */
    remove(): void;
}

/** Minimal MapLibre map surface used by `DemSource.addTo()`. */
export type IsobandMap = Pick<
    Map,
    'addSource' | 'addLayer' | 'addControl' | 'removeControl' |
    'getLayer' | 'removeLayer' | 'getSource' | 'removeSource'
>;

export interface IsobandSourceSpecification extends VectorSourceSpecification {
    type: 'vector';
    encoding: 'mlt';
}

export interface TileCoordinate {
    z: number;
    x: number;
    y: number;
}

export interface IsobandGenerationOptions {
    thresholds: number[];
    /** Include the unbounded band below the first threshold. Defaults to false. */
    includeLower?: boolean;
    /** Include the unbounded band above the final threshold. Defaults to true. */
    includeUpper?: boolean;
    extent?: number;
    buffer?: number;
}

export type Position = [number, number];
export type Ring = Position[];
export type Polygon = Ring[];
export type MultiPolygon = Polygon[];

export interface GeneratedIsoband {
    properties: IsobandProperties;
    geometry: MultiPolygon;
}
